[build]
  command = "npm run build"
  publish = "client/.next"
  functions = "client/.netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/next-runtime"
