name: Netlify Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dry-run:
    name: Dry Run Netlify Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Run Netlify Build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
        run: |
          cd client
          netlify build --dry

  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: dry-run

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Build Next.js for Netlify
        run: |
          cd client
          npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          cd client
          netlify deploy --dir=.next --functions=.netlify/functions --prod
