name: Dry Run Netlify Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  netlify-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Run Netlify Build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
        run: |
          cd client
          netlify build
